// <auto-generated />
using System;
using DBLib.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBLib.Migrations
{
    [DbContext(typeof(AuthenTokenContext))]
    [Migration("20210525040940_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("DBLib.Models.Token", b =>
                {
                    b.Property<string>("TokenID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpireDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockRefresh")
                        .HasColumnType("INTEGER");

                    b.HasKey("TokenID");

                    b.ToTable("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
